### ISSUE TITLE
[TV SME.sk] podcast-box not found!

### ISSUE THREAD

**Issue by mmihal** [kodi-czsk/plugin.video.tv.sme.sk#2]
vsimol som si ze videa sa nedaju prehrat. V logu skonci len toto

16:32:11.341 T:1023402752   ERROR: [TV SME.sk] podcast-box not found!
16:32:11.586 T:1023402752   ERROR: [TV SME.sk] Player script not found!
16:32:11.662 T:1925851648   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tv.sme.sk/?url=http%3A%2F%2Ftv.sme.sk%2Fv%2F32972%2Falojz-hlina-sis-nerobi-to-co-ma-platime-klebetne-baby.html&mode=5&name=%2815.+1.+2016+o+12%3A47%29+Alojz+Hlina%3A+SIS+nerob%C3%AD+to%2C+%C4%8Do+m%C3%A1.+Plat%C3%ADme+klebetn%C3%A9+baby&desc=%C4%8Co+si+mysl%C3%AD+poslanec+NR+SR+o+spisoch+Gorila%3F]

**Comment by kapitan-iglu** [comment]
Vdaka za report, pozriem sa na to.
